# Generated by Django 3.2.4 on 2021-06-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='named',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='named',
            new_name='name',
        ),
    ]
